-- Script para ser rodado no servidor espelho
Use Master
go

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'tech4bmaster!@#$';
GO

USE master;
CREATE CERTIFICATE MIRROR_BRJAGCCCISQLP02_cert 
   WITH SUBJECT = 'MIRROR_BRJAGCCCISQLP02 certificado para o servidor MIRROR',
   EXPIRY_DATE = '12/30/2029';
GO

CREATE ENDPOINT Mirroring
   STATE = STARTED
   AS TCP (
      LISTENER_PORT=5024
      , LISTENER_IP = ALL
   ) 
   FOR DATABASE_MIRRORING ( 
      AUTHENTICATION = CERTIFICATE MIRROR_BRJAGCCCISQLP02_cert
      , ENCRYPTION = REQUIRED ALGORITHM RC4
      , ROLE = ALL
   );
GO

BACKUP CERTIFICATE MIRROR_BRJAGCCCISQLP02_cert TO FILE = 'D:\config_mirror\MIRROR_BRJAGCCCISQLP02_cert.cer';
GO

USE master;
CREATE LOGIN MASTER_BRJAGCCCISQLP01_login WITH PASSWORD = 'tech4bmaster!@#$';
GO

CREATE USER MASTER_BRJAGCCCISQLP01_user FOR LOGIN MASTER_BRJAGCCCISQLP01_login;
GO

CREATE CERTIFICATE MASTER_BRJAGCCCISQLP01_cert
   AUTHORIZATION MASTER_BRJAGCCCISQLP01_user
   FROM FILE = 'D:\config_mirror\MASTER_BRJAGCCCISQLP01_cert.cer' 
GO

GRANT CONNECT ON ENDPOINT::Mirroring TO [MASTER_BRJAGCCCISQLP01_login];
GO

ALTER DATABASE cmcSiteCaue 
    SET PARTNER = 'TCP://BRJAGCCCISQLP01.GCC.COM:5024';
GO
ALTER DATABASE SharedServices1_Search_DB 
    SET PARTNER = 'TCP://BRJAGCCCISQLP01.GCC.COM:5024';
GO
ALTER DATABASE SharedServicesCaue_DB 
    SET PARTNER = 'TCP://BRJAGCCCISQLP01.GCC.COM:5024';
GO
ALTER DATABASE "SharePoint_AdminContent_327c740f-49cf-4034-9e34-4fd444e9db5a" 
    SET PARTNER = 'TCP://BRJAGCCCISQLP01.GCC.COM:5024';
GO
ALTER DATABASE SharePoint_Config 
    SET PARTNER = 'TCP://BRJAGCCCISQLP01.GCC.COM:5024';
GO
ALTER DATABASE WSS_Content 
    SET PARTNER = 'TCP://BRJAGCCCISQLP01.GCC.COM:5024';
GO
ALTER DATABASE WSS_Search_BRJAGCCCISQLP02 
    SET PARTNER = 'TCP://BRJAGCCCISQLP01.GCC.COM:5024';
GO

ALTER DATABASE t4bdb01 
    SET PARTNER = 'TCP://BRJAGCCCISQLP01.GCC.COM:5024';
GO

USE master;
CREATE LOGIN WITNESS_BRJAGCCCISQLP02_login WITH PASSWORD = 'tech4bmaster!@#$';
GO

CREATE USER WITNESS_BRJAGCCCISQLP02_user FOR LOGIN WITNESS_BRJAGCCCISQLP02_login;
GO

CREATE CERTIFICATE WITNESS_BRJAGCCCISQLP02_cert
   AUTHORIZATION WITNESS_BRJAGCCCISQLP02_user
   FROM FILE = 'D:\config_mirror\WITNESS_BRJAGCCCISQLP02_cert.cer' 
GO

GRANT CONNECT ON ENDPOINT::Mirroring TO [WITNESS_BRJAGCCCISQLP02_login];
GO