-- Script para ser rodado no servidor Witness
Use Master
go

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'tech4bmaster!@#$';
GO

USE master;
CREATE CERTIFICATE WITNESS_BRJAGCCCISQLP02_cert 
   WITH SUBJECT = 'WITNESS_BRJAGCCCISQLP02 certificado para o servidor WITNESS',
   EXPIRY_DATE = '12/30/2029';
GO

CREATE ENDPOINT Mirroring
   STATE = STARTED
   AS TCP (
      LISTENER_PORT=7022
      , LISTENER_IP = ALL
   ) 
   FOR DATABASE_MIRRORING ( 
      AUTHENTICATION = CERTIFICATE WITNESS_BRJAGCCCISQLP02_cert
      , ENCRYPTION = REQUIRED ALGORITHM RC4
      , ROLE = WITNESS
   );
GO

BACKUP CERTIFICATE WITNESS_BRJAGCCCISQLP02_cert TO FILE = 'D:\config_mirror\WITNESS_BRJAGCCCISQLP02_cert.cer';
GO

USE master;
CREATE LOGIN MIRROR_BRJAGCCCISQLP02_login WITH PASSWORD = 'tech4bmaster!@#$';
GO

CREATE USER MIRROR_BRJAGCCCISQLP02_user FOR LOGIN MIRROR_BRJAGCCCISQLP02_login;
GO

CREATE CERTIFICATE MIRROR_BRJAGCCCISQLP02_cert
   AUTHORIZATION MIRROR_BRJAGCCCISQLP02_user
   FROM FILE = 'D:\config_mirror\MIRROR_BRJAGCCCISQLP02_cert.cer' 
GO

GRANT CONNECT ON ENDPOINT::Mirroring TO [MIRROR_BRJAGCCCISQLP02_login];
GO

USE master;
CREATE LOGIN MASTER_BRJAGCCCISQLP01_login WITH PASSWORD = 'tech4bmaster!@#$';
GO

CREATE USER MASTER_BRJAGCCCISQLP01_user FOR LOGIN MASTER_BRJAGCCCISQLP01_login;
GO

CREATE CERTIFICATE MASTER_BRJAGCCCISQLP01_cert
   AUTHORIZATION MASTER_BRJAGCCCISQLP01_user
   FROM FILE = 'D:\config_mirror\MASTER_BRJAGCCCISQLP01_cert.cer' 
GO

GRANT CONNECT ON ENDPOINT::Mirroring TO [MASTER_BRJAGCCCISQLP01_login];
GO

